cg/server/invoices/views.py
import os
import tempfile
from datetime import date

from flask import flash, Blueprint, render_template, request, redirect, url_for, \
    send_from_directory, session
from flask_dance.contrib.google import google

from cg.apps.invoice.render import render_xlsx
from cg.meta.invoice import InvoiceAPI
from cg.server.ext import db, lims

BLUEPRINT = Blueprint('invoices', __name__, template_folder='templates')


def logged_in():
    user_obj = db.user(session.get('user_email'))
    return google.authorized and user_obj and user_obj.is_admin


def undo_invoice(invoice_id):
    invoice_obj = db.invoice(invoice_id)
    record_type = invoice_obj.record_type
    records = db.invoice_samples(invoice_id=invoice_id)
    invoice_obj.delete()
    for record in records:
        record.invoice_id = None
    db.session.commit()

    return url_for('.new', record_type=record_type)


def make_new_invoice():
    customer_id = request.form.get('customer')
    customer_obj = db.customer(customer_id)
    record_ids = request.form.getlist('records')
    record_type = request.form.get('record_type')
    if len(record_ids) == 0:
        return redirect(url_for('.new', record_type=record_type))
    if record_type == 'Pool':
        pools = [db.pool(pool_id) for pool_id in record_ids]
        new_invoice = db.add_invoice(
            customer=customer_obj,
            pools=pools,
            comment=request.form.get('comment'),
            discount=int(request.form.get('discount', '0')),
            record_type='Pool')
    elif record_type == 'Sample':
        samples = [db.sample(sample_id) for sample_id in record_ids]
        new_invoice = db.add_invoice(
            customer=customer_obj,
            samples=samples,
            comment=request.form.get('comment'),
            discount=int(request.form.get('discount', '0')),
            record_type='Sample')
    elif record_type == 'Microbial':
        microbial_samples = [db.microbial_sample(sample_id) for sample_id in record_ids]
        new_invoice = db.add_invoice(
            customer=customer_obj,
            microbial_samples=microbial_samples,
            comment=request.form.get('comment'),
            discount=int(request.form.get('discount', '0')),
            record_type='Microbial')

    db.add_commit(new_invoice)
    return url_for('.invoice', invoice_id=new_invoice.id)


def upload_invoice_news_to_db():
    invoice_id = request.form.get('invoice_id')
    invoice_obj = db.invoice(invoice_id)
    invoice_obj.comment = request.form.get('comment')

    if request.form.get('final_price') != invoice_obj.price:
        invoice_obj.price = request.form.get('final_price')
        final_price = request.form.get('final_price')

    if request.form.get('invoice_sent') and not invoice_obj.invoiced_at:
        invoice_obj.invoiced_at = date.today()
    elif not request.form.get('invoice_sent'):
        invoice_obj.invoiced_at = None

    kth_excel_file = request.files.get('KTH_excel')
    if kth_excel_file:
        invoice_obj.excel_kth = kth_excel_file.stream.read()
    ki_excel_file = request.files.get('KI_excel')
    if ki_excel_file:
        invoice_obj.excel_ki = ki_excel_file.stream.read()
    db.commit()
    return url_for('invoices.invoice', invoice_id=invoice_id)


@BLUEPRINT.route('/', methods=['GET', 'POST'])
def index():
    """Show invoices."""
    if not logged_in(): return redirect(url_for('admin.index'))

    if request.form.get('new_invoice_updates'):
        url = upload_invoice_news_to_db()
        return redirect(url)
    elif request.form.get('undo'):
        invoice_id = request.form.get('invoice_id')
        url = undo_invoice(invoice_id)
        return redirect(url)
    elif request.method == 'POST':
        url = make_new_invoice()
        return redirect(url)
    else:
        invoices = {'sent_invoices': db.invoices(invoiced=True),
                    'pending_invoices': db.invoices(invoiced=False)}
        return render_template('invoices/index.html', invoices=invoices)


@BLUEPRINT.route('/new/<record_type>')
def new(record_type):
    """Generate a new invoice."""
    if not logged_in(): return redirect(url_for('admin.index'))

    count = request.args.get('total', 0)
    customer_id = request.args.get('customer', 'cust002')
    customer_obj = db.customer(customer_id)

    if record_type == 'Sample':
        records, customers_to_invoice = db.samples_to_invoice(customer=customer_obj)
    elif record_type == 'Pool':
        records, customers_to_invoice = db.pools_to_invoice(customer=customer_obj)
    elif record_type == 'Microbial':
        records, customers_to_invoice = db.microbial_samples_to_invoice(customer=customer_obj)

    return render_template(
        'invoices/new.html',
        customers_to_invoice=customers_to_invoice,
        count=count,
        records=records,
        record_type=record_type,
        args={'customer': customer_id})


@BLUEPRINT.route('/<int:invoice_id>', methods=['GET', 'POST'])
def invoice(invoice_id):
    """Save comments and uploaded modified invoices."""
    if not logged_in(): return redirect(url_for('admin.index'))

    invoice_obj = db.invoice(invoice_id)
    api = InvoiceAPI(db, lims, invoice_obj)
    kth_inv = api.prepare('KTH')
    ki_inv = api.prepare('KI')

    if not (kth_inv and ki_inv):
        flash(' ,'.join(list(set(api.log))))
        url = undo_invoice(invoice_id)
        return redirect(request.referrer)

    if not invoice_obj.price:
        final_price = api.total_price()
    else:
        final_price = invoice_obj.price

    return render_template('invoices/invoice.html',
                           invoice=invoice_obj,
                           invoice_dict={'KTH': kth_inv, 'KI': ki_inv},
                           default_price=api.total_price(),
                           final_price=final_price,
                           record_type=invoice_obj.record_type)


@BLUEPRINT.route('/<int:invoice_id>/excel')
def invoice_template(invoice_id):
    """Generate invoice template"""
    if not logged_in(): return redirect(url_for('admin.index'))

    cost_center = request.args.get('cost_center', 'KTH')
    invoice_obj = db.invoice(invoice_id)
    api = InvoiceAPI(db, lims, invoice_obj)

    # api = InvoiceAPI(db, lims, invoice_id)
    invoice_dict = api.prepare(cost_center)
    workbook = render_xlsx(invoice_dict)

    temp_dir = tempfile.gettempdir()
    fname = "Invoice_{}_{}.xlsx".format(invoice_obj.id, cost_center)
    excel_path = os.path.join(temp_dir, fname)
    workbook.save(excel_path)

    return send_from_directory(directory=temp_dir, filename=fname, as_attachment=True)


@BLUEPRINT.route('/<int:invoice_id>/invoice_file/<cost_center>')
def modified_invoice(invoice_id, cost_center):
    """Enables download of modified invoices saved in the database."""
    if not logged_in(): return redirect(url_for('admin.index'))

    invoice_obj = db.invoice(invoice_id)
    file_name = 'invoice_' + cost_center + str(invoice_id) + '.xlsx'
    temp_dir = tempfile.mkdtemp()
    file_path = os.path.join(temp_dir, file_name)

    with open(file_path, 'wb') as file_object:
        if cost_center == 'KTH':
            file_object.write(invoice_obj.excel_kth)
        elif cost_center == 'KI':
            file_object.write(invoice_obj.excel_ki)
        pass
    return send_from_directory(directory=temp_dir, filename=file_name, as_attachment=True)

cg/server/invoices/templates/invoices/index.html
{% extends 'invoices/layout.html' %}

{% block body %}
<div class="container mt-5 mb-5">
  <h1>Invoices</h1>
  <br><br>


  <ul class="nav nav-tabs">
      <li class="nav-item"><a href="" data-target="#Pending" data-toggle="tab" class="nav-link active">Pending</a></li>
      <li class="nav-item"><a href="" data-target="#Sent" data-toggle="tab" class="nav-link">Sent</a></li>
  </ul>
  <div id="tabsJustifiedContent" class="tab-content">
      <div id="Pending" class="tab-pane fade active show">
          {{ invoice_table(invoices['pending_invoices'] ,'No pending invoices.', 'pending') }}
      </div>
      <div id="Sent" class="tab-pane show">
          {{ invoice_table(invoices['sent_invoices'] ,'No delivered invoices.', 'sent') }}
      </div>
  </div>

</div>
{% endblock %}


{% macro invoice_table(invoices ,no_invoice, status) %}
<div class="card">
  {% if invoices.all() %}
  <br>
<table id={{status}} class="table" cellspacing="0" width="100%">
    <thead>
    <tr>
      <th>Invoice ID</th>
      <th>Customer</th>
      <th>Created at</th>
      <th>Invoiced at</th>
      <th>Nr samples</th>
      {% if status=='sent' %}
      <th>Price</th>
      {% endif %}
    </tr>
    </thead>
    <tbody>
    {% for invoice in invoices %}
    <tr>
      <td>
      <a href="{{ url_for('invoices.invoice', invoice_id=invoice.id) }}">
        {{ invoice.id }}
      </a>
      </td>
      <td>{{ invoice.customer.internal_id}} - {{ invoice.customer.name }}</td>
      <td>{% if invoice.created_at!=None %}{{ invoice.created_at.strftime('%Y-%m-%d') }}{% endif %}</td>
      <td>{% if invoice.invoiced_at!=None %} {{ invoice.invoiced_at.strftime('%Y-%m-%d')  }} {% endif %}</td>
      <td>{% if invoice.microbial_samples %}{{ invoice.microbial_samples|count }}{% else %}{{ invoice.samples|count }}{% endif %}</td>
      {% if status=='sent' %}
      <td>{{ invoice.price }}</td>
      {% endif %}
    </tr>
    {% endfor %}
  </tbody>
  </table>
  {% else %}
  <li class="list-group-item">{{no_invoice}}</li>
  {% endif %}
</div>
{% endmacro %}

{% block scripts %}
<script language="JavaScript">
$(document).ready(function() {
    var table = $('#pending').DataTable( {
        lengthChange: false,
        buttons: [ 'copy', 'excel', 'pdf' ]
    } );
 
    table.buttons().container()
    
        .appendTo( "#pending_wrapper .col-md-6:eq(0)" );
} );

$(document).ready(function() {
    var table = $('#sent').DataTable( {
        lengthChange: false,
        buttons: [ 'copy', 'excel', 'pdf']
    } );
 
    table.buttons().container()
    
        .appendTo( "#sent_wrapper .col-md-6:eq(0)" );
} );
</script>

<script src="//code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.1/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.bootstrap4.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
<script src="//cdn.datatables.net/buttons/1.5.1/js/buttons.html5.min.js"></script>
<script src="//cdn.datatables.net/buttons/1.5.1/js/buttons.print.min.js"></script>
<script src="//cdn.datatables.net/buttons/1.5.1/js/buttons.colVis.min.js"></script>

{% endblock %}

cg/server/invoices/templates/invoices/layout.html
<!doctype html>
<html lang="en">

<head>
  <title>Invoices - Clinical Genomics</title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta
    name="viewport"
    content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css">
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
              <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('invoices.index')}}">Invoices</a>
              </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  New Invoice
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{{ url_for('invoices.new', record_type = 'Sample')}}">Samples</a>
                  <a class="dropdown-item" href="{{ url_for('invoices.new', record_type = 'Pool')}}">Pools</a>
                  <a class="dropdown-item" href="{{ url_for('invoices.new', record_type = 'Microbial')}}">Microbial</a>
                </div>
              </li>
          </ul>
        </div>
      </nav>

  {% with messages = get_flashed_messages() %}
    {% if messages %}
        <div class=flashes>
        {% for message in messages %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endfor %}
        </div>
      {% endif %}
    {% endwith %}  
  {% block body %}{% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    {% block scripts %}{% endblock %}  
</body>

</html>

cg/server/invoices/templates/invoices/new.html
{% extends 'invoices/layout.html' %}

{% block body %}
<div class="container mt-5 mb-5">
  <h1>Make new invoice ({{record_type}})</h1>
  <br>
  <form action="{{ url_for('invoices.new', record_type=record_type) }}">
    <input type="hidden" name="record_type" value="{{ record_type }}">
    <div class="row">
      <div class="col">
        <select name="customer" class="form-control" required>
          <option>Select customer...</option>
          {% for customer in customers_to_invoice %}
          <option value="{{ customer.internal_id }}" {{ 'selected' if args.customer == customer.internal_id }}>
            {{ customer.internal_id}} - {{customer.name }}
          </option>
          {% endfor %}
        </select>
      </div>
      <div class="col">
        <button class="btn btn-primary">Load {{record_type}}s</button>
      </div>
    </div>
  </form>
  <form name="listForm" action="{{ url_for('invoices.index')}}" method="POST" class="mt-3">
    <input type="hidden" name="customer" value="{{ args.customer }}">
    <input type="hidden" name="record_type" value="{{record_type}}">
    <label>Discount (%)</label>
    <input type="number" class="form-control" name="discount" value="0">
    <div class="form-group">
      <label>Comment</label>
      <textarea class="form-control" name="comment" rows="3"></textarea>
    </div>

    Total Price Standard: <input type="text" size="7" name="total" value="0"/>
    <button class="btn btn-primary float-right" type="submit">Generate invoice</button>    
    <tr><input type="checkbox" onClick="check_all()" /> Select all</tr>
    <tr><input type="checkbox" onClick="check_subset()" /> Select Subset</tr>
    <br><br><br>
    <div class="container">
      <input class="form-control" id="Search" type="text" placeholder="Search..">
      <br>
    <table class="table">
      <thead>
      <tr>
        <th>{{record_type}}</th>
        <th>Customer</th>
        <th>Order</th>
        <th>Ticket</th>
        <th>Application</th>
        <th>Created at</th>
        <th>Delivered at</th>
        <th>Price: Stan/Prio/Res/Expr</th>
      </tr>
      </thead>
      <tbody id="myTable">
      {% for record in records %}
      <tr>
        <td>
          <label class="form-check-label">
            {%if record_type=='Pool'%}
            <input class="form-check-input" onchange="checkTotal()" type="checkbox" name="records" id="{{ record.application_version.price_standard }}"  value="{{ record.id }}"> {{ record.id }}
            {% else %}
            <input class="form-check-input" onchange="checkTotal()" type="checkbox" name="records" id="{{ record.application_version.price_standard }}" value="{{ record.internal_id }}"> {{ record.internal_id }}            
            {%endif%}            
          </label>
        </td>
        <td> {% if record_type=='Microbial'%}{{ record.microbial_order.customer.name }} {% else %} {{ record.customer.name }}{% endif %}</td>
        <td>{% if record_type=='Microbial'%}{{ record.microbial_order.id }} {% else %} {{ record.order}}{% endif %}</td>
        <td>{% if record_type=='Microbial'%}{{ record.microbial_order.ticket_number }} {% else %} {{ record.ticket_number}}{% endif %}</td>
        <td>{{ record.application_version.application.tag }}</td> 
        <td>{{record.created_at.date()}}</td>
        <td>{{record.delivered_at.date()}}</td>
        <td>{% if record.application_version.price_standard %}{{record.application_version.price_standard}}{% else %}{% endif %}/
            {% if record.application_version.price_priority %}{{record.application_version.price_priority}}{% else %}{% endif %}/
            {% if record.application_version.price_research %}{{record.application_version.price_research}}{% else %}{% endif %}/
            {% if record.application_version.price_express %}{{record.application_version.price_express}}{% else %}{% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
    </table>
  </div>
  </form>
</div>
{% endblock %}


{% block scripts %}

<script language="JavaScript"> 

  function check_all() {
    $("input[name='records']").each(function() {
      this.checked = !this.checked
    })
    checkTotal()
  }

  function check_subset() {
    total_price = 0;
    $("input[name='records']").each(function() {
      if (total_price <= 500000) {
        this.checked = !this.checked
        total_price += parseInt(this.id)
      }
    })
    checkTotal()
  }

  function checkTotal() {
    value = 0
    $("input[name='records']:checked").each(function() {
      value += parseInt(this.id)
    })
    $("input[name='total']").val(value)
  }

  $(document).ready(function(){
    $("#Search").on("keyup", function() {
      var value = $(this).val().toLowerCase();
      $("#myTable tr").filter(function() {
        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
      });
    });
  });
  </script>
{% endblock %}